-- Seed data for Imigrantes Floripa.
--
-- The MVP keeps the content in TypeScript (`src/lib/data/*.ts`) so the public
-- site works without a Supabase project. When you're ready to migrate:
--   1. Apply `migrations/0001_initial_schema.sql` in the Supabase SQL editor.
--   2. Run the migration helper script (TODO: scripts/migrate-mock-to-supabase.ts)
--      to insert the contents of `src/lib/data/*.ts` into the tables below.
--   3. Promote your user to admin:
--        update profiles set role = 'admin' where id = '<your-auth-user-uuid>';
--
-- Until then this file is intentionally empty.
