-- Initial schema for Imigrantes Floripa
-- Content tables use the pattern: base table + _translations table keyed by (id, locale)
-- so adding a new language is just inserts, not migrations.

create type locale as enum ('pt', 'es');

-- ------------------------------------------------------------
-- Content
-- ------------------------------------------------------------

create table modules (
  id           bigint generated by default as identity primary key,
  slug         text unique not null,
  order_index  int not null default 0,
  icon         text,
  published    boolean not null default true,
  created_at   timestamptz not null default now()
);

create table module_translations (
  module_id      bigint not null references modules(id) on delete cascade,
  locale         locale not null,
  title          text not null,
  summary        text not null,
  body_markdown  text not null,
  primary key (module_id, locale)
);

create table categories (
  id           bigint generated by default as identity primary key,
  slug         text unique not null,
  order_index  int not null default 0,
  icon         text
);

create table category_translations (
  category_id  bigint not null references categories(id) on delete cascade,
  locale       locale not null,
  name         text not null,
  primary key (category_id, locale)
);

create table contacts (
  id           bigint generated by default as identity primary key,
  category_id  bigint references categories(id) on delete set null,
  phone        text,
  whatsapp     text,
  email        text,
  address      text,
  lat          numeric,
  lng          numeric,
  website      text,
  hours        text,
  published    boolean not null default true,
  created_at   timestamptz not null default now()
);

create table contact_translations (
  contact_id   bigint not null references contacts(id) on delete cascade,
  locale       locale not null,
  name         text not null,
  description  text not null,
  primary key (contact_id, locale)
);

create table module_contacts (
  module_id   bigint not null references modules(id) on delete cascade,
  contact_id  bigint not null references contacts(id) on delete cascade,
  primary key (module_id, contact_id)
);

-- ------------------------------------------------------------
-- Users
-- ------------------------------------------------------------

create table profiles (
  id                uuid primary key references auth.users(id) on delete cascade,
  role              text not null default 'user' check (role in ('user', 'admin')),
  preferred_locale  locale not null default 'pt',
  created_at        timestamptz not null default now()
);

create table user_progress (
  user_id       uuid not null references auth.users(id) on delete cascade,
  module_id     bigint not null references modules(id) on delete cascade,
  completed_at  timestamptz not null default now(),
  primary key (user_id, module_id)
);

-- Auto-create a profile row whenever a new user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ------------------------------------------------------------
-- Row Level Security
-- ------------------------------------------------------------

alter table modules                enable row level security;
alter table module_translations    enable row level security;
alter table categories             enable row level security;
alter table category_translations  enable row level security;
alter table contacts               enable row level security;
alter table contact_translations   enable row level security;
alter table module_contacts        enable row level security;
alter table profiles               enable row level security;
alter table user_progress          enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Public read for published content (admins see everything).
create policy "Public read modules" on modules
  for select using (published = true or public.is_admin());
create policy "Public read module translations" on module_translations
  for select using (
    exists (
      select 1 from modules m
      where m.id = module_translations.module_id
        and (m.published or public.is_admin())
    )
  );
create policy "Public read categories" on categories for select using (true);
create policy "Public read category translations" on category_translations for select using (true);
create policy "Public read contacts" on contacts
  for select using (published = true or public.is_admin());
create policy "Public read contact translations" on contact_translations
  for select using (
    exists (
      select 1 from contacts c
      where c.id = contact_translations.contact_id
        and (c.published or public.is_admin())
    )
  );
create policy "Public read module contacts" on module_contacts for select using (true);

-- Admin can write everything.
create policy "Admin write modules" on modules
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write module translations" on module_translations
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write categories" on categories
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write category translations" on category_translations
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write contacts" on contacts
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write contact translations" on contact_translations
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write module contacts" on module_contacts
  for all using (public.is_admin()) with check (public.is_admin());

-- Profile policies: users see/update their own row; only admins change roles.
create policy "Users see own profile" on profiles
  for select using (auth.uid() = id);
create policy "Users update own profile" on profiles
  for update using (auth.uid() = id)
  with check (auth.uid() = id);
create policy "Admin manage profiles" on profiles
  for all using (public.is_admin()) with check (public.is_admin());

-- Progress: each user owns their rows.
create policy "Users read own progress" on user_progress
  for select using (auth.uid() = user_id);
create policy "Users insert own progress" on user_progress
  for insert with check (auth.uid() = user_id);
create policy "Users update own progress" on user_progress
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users delete own progress" on user_progress
  for delete using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------

create index modules_order_idx           on modules(order_index);
create index contacts_category_idx       on contacts(category_id);
create index user_progress_user_idx      on user_progress(user_id);
create index module_contacts_module_idx  on module_contacts(module_id);
create index module_contacts_contact_idx on module_contacts(contact_id);
